### ISSUE TITLE
Broken url in img tag when referenced filename contains '#'

### ISSUE THREAD

**Issue by bauerandreas** [ADmad/cakephp-glide#24]
The GlideHelper::image() method generates a img tag with a cut off src attribute when the filename contains a # character. Other characters were not tested.

**Comment by ADmad** [comment]
Feel free to submit a patch with tests to fix it. I personally always cleanup my file names to avoid such problems.

**Comment by bauerandreas** [comment]
You're right, that should be the way to go, also this was my solution to process the filenames before saving.

**Comment by ADmad** [comment]
That's the sensible thing to do :slightly_smiling_face:.
