### ISSUE TITLE
nice stuff, very fluid and easy to work with. However watermarks are pesky...

### ISSUE THREAD

**Issue by sams** [ADmad/cakephp-glide#5]
I think its a simple oversight to do with paths to the watermark

ive tried adding mark or watermark to the params array. I have tried adding settings to the configure array. I cant seem to track down the issue. Watermarks are not in the tests either

could you add some info to the documentation?

**Comment by ADmad** [comment]
I haven't using watermarking myself yet. Show me some actual code you have used based on [glide's  docs](http://glide.thephpleague.com/1.0/api/watermarks/) and I can try to help debug the problem.

**Comment by sams** [comment]
there is this but, I have added it but am not yet getting any juice 
```

    'watermarks' => new Filesystem(new Local('path/to/watermarks/folder')),
    'watermarks_path_prefix' => 'files/watermarks', // optional

    'mark' => 'watermark.png',
    'markw' => '30w',
    'markpad' => '5w',

```

I have a configure file glide.php in config that i load with ``` Configure::load('glide', 'default'); ``` in bootstrap before I load the plugin.

**Comment by ADmad** [comment]
The `'watermarks'` and `'watermarks_path_prefix'` would go directly under `serverConfig` and the rest under ['presets`](http://glide.thephpleague.com/1.0/config/defaults-and-presets/#presets) or in URL querystring.
